name: Automated Docds workflow
on:
  push:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.safayatjakir }}
          password: ${{ secrets.----------- }}

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: safayatjakir/docdsv2:latest